version: "3"

services:
    lsgraph:
        build: ./
        expose:
          - "5000"
        ports:
          - "5000:5000"
        volumes:
          - "./:/app/app"
        env_file: .env
        working_dir: /app/app
        command: ./start.sh
        links:
          - lsdatabase

    lsdatabase:
        image: postgres:11
        volumes:
          - lsdb_data:/var/lib/postgresql
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
        expose:
          - "5432"
        ports:
          - "5432:5432"


volumes:
    lsdb_data:
        driver: local
