version: "3"

services:
    lsgraph:
        build:
          context: .
          dockerfile: ./compose/web/Dockerfile
        image: lsgraph_web
        expose:
          - "5000"
        ports:
          - "5000:5000"
        volumes:
          - "./:/app/app"
        env_file: .env
        working_dir: /app/app
        command: ./start.sh
        links:
          - lsdatabase
          - lsbroker

    lsdatabase:
        image: postgres:12
        volumes:
          - lsdb_data:/var/lib/postgresql
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
        expose:
          - "5432"
        ports:
          - "5432:5432"

    lsbroker:
      image: rabbitmq:3.9-management
      expose:
        - "5672"
      ports:
        - "5672:5672"
        - "15672:15672"

    lsworker:
        build:
          context: .
          dockerfile: ./compose/worker/Dockerfile
        image: lsgraph_worker
        volumes:
          - "./:/app/app"
        env_file: .env
        working_dir: /app/app
        command: ./start_celery_worker.sh
        links:
          - lsdatabase
          - lsbroker



volumes:
    lsdb_data:
        driver: local
