"""Add organization ID to offering, format, provider, and platform tables

Revision ID: 19c82d01b4e4
Revises: d415315f23d6
Create Date: 2021-08-03 20:07:17.008812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19c82d01b4e4'
down_revision = 'd415315f23d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('format', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_format_organization_id'), 'format', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'format', 'organization', ['organization_id'], ['id'])
    op.add_column('offering', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_offering_organization_id'), 'offering', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'offering', 'organization', ['organization_id'], ['id'])
    op.add_column('platform', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_platform_organization_id'), 'platform', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'platform', 'organization', ['organization_id'], ['id'])
    op.add_column('provider', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_provider_organization_id'), 'provider', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'provider', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_index(op.f('ix_provider_organization_id'), table_name='provider')
    op.drop_column('provider', 'organization_id')
    op.drop_constraint(None, 'platform', type_='foreignkey')
    op.drop_index(op.f('ix_platform_organization_id'), table_name='platform')
    op.drop_column('platform', 'organization_id')
    op.drop_constraint(None, 'offering', type_='foreignkey')
    op.drop_index(op.f('ix_offering_organization_id'), table_name='offering')
    op.drop_column('offering', 'organization_id')
    op.drop_constraint(None, 'format', type_='foreignkey')
    op.drop_index(op.f('ix_format_organization_id'), table_name='format')
    op.drop_column('format', 'organization_id')
    # ### end Alembic commands ###
