"""Connect organization to skills graph

Revision ID: 1bd37946439c
Revises: 416c03e7a685
Create Date: 2021-05-25 13:27:00.416788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1bd37946439c"
down_revision = "416c03e7a685"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "level", ["id"])
    op.add_column(
        "organization",
        sa.Column("root_skill_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "organization", "skill", ["root_skill_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_column("organization", "root_skill_id")
    op.drop_constraint(None, "level", type_="unique")
    # ### end Alembic commands ###
