"""Add retired to offering

Revision ID: 21a62b326436
Revises: e5ba5eb44e82
Create Date: 2021-08-04 23:11:31.284081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a62b326436'
down_revision = 'e5ba5eb44e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offering', sa.Column('retired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offering', 'retired')
    # ### end Alembic commands ###
