"""Add full text search for resources

Revision ID: 5f41694025a0
Revises: 869e7165ee21
Create Date: 2021-08-17 22:10:31.755001

"""
from alembic import op
import sqlalchemy as sa

import lsgraph


# revision identifiers, used by Alembic.
revision = '5f41694025a0'
down_revision = '869e7165ee21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('__ts_vector__', lsgraph.models._shared.TSVECTOR(), sa.Computed("to_tsvector('english', name || ' ' || short_description || ' ' || description)", persisted=True), nullable=True))
    op.create_index('ix_name_desc_ts_vector__', 'resource', ['__ts_vector__'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_name_desc_ts_vector__', table_name='resource')
    op.drop_column('resource', '__ts_vector__')
    # ### end Alembic commands ###
