"""Add full text search for skills

Revision ID: 6fa9e98b26df
Revises: 5f41694025a0
Create Date: 2021-08-22 18:56:04.922977

"""
from alembic import op
import sqlalchemy as sa

import lsgraph

# revision identifiers, used by Alembic.
revision = '6fa9e98b26df'
down_revision = '5f41694025a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('__ts_vector__', lsgraph.models._shared.TSVECTOR(), sa.Computed("to_tsvector('english', name)", persisted=True), nullable=True))
    op.create_index('ix_skill_name__ts_vector__', 'skill', ['__ts_vector__'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_name__ts_vector__', table_name='skill')
    op.drop_column('skill', '__ts_vector__')
    # ### end Alembic commands ###
