"""Add organization ID to collection

Revision ID: 869e7165ee21
Revises: 21a62b326436
Create Date: 2021-08-13 21:05:44.077233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '869e7165ee21'
down_revision = '21a62b326436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_collection_organization_id'), 'collection', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'collection', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_index(op.f('ix_collection_organization_id'), table_name='collection')
    op.drop_column('collection', 'organization_id')
    # ### end Alembic commands ###
