"""empty message

Revision ID: 8ecfe7dd657c
Revises: efb52387ae38
Create Date: 2021-06-10 14:18:44.370684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ecfe7dd657c'
down_revision = 'efb52387ae38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_user_organization_id'), 'user', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_organization_id'), table_name='user')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###
