"""empty message

Revision ID: d415315f23d6
Revises: f2ddf091e352
Create Date: 2021-07-08 14:14:43.006879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd415315f23d6'
down_revision = 'f2ddf091e352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('resource_recommendation_vector', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'resource_recommendation_vector')
    # ### end Alembic commands ###
