"""Add organization ID to resources

Revision ID: e5ba5eb44e82
Revises: 19c82d01b4e4
Create Date: 2021-08-03 23:32:48.648252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5ba5eb44e82'
down_revision = '19c82d01b4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_resource_organization_id'), 'resource', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'resource', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_index(op.f('ix_resource_organization_id'), table_name='resource')
    op.drop_column('resource', 'organization_id')
    # ### end Alembic commands ###
