"""empty message

Revision ID: efb52387ae38
Revises: 1bd37946439c
Create Date: 2021-05-26 09:40:49.340468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "efb52387ae38"
down_revision = "1bd37946439c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group",
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column("group", sa.Column("whole_organization", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_group_organization_id"), "group", ["organization_id"], unique=False
    )
    op.create_foreign_key(None, "group", "organization", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_index(op.f("ix_group_organization_id"), table_name="group")
    op.drop_column("group", "whole_organization")
    op.drop_column("group", "organization_id")
    # ### end Alembic commands ###
