"""empty message

Revision ID: f2ddf091e352
Revises: 8ecfe7dd657c
Create Date: 2021-07-08 14:13:13.545311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2ddf091e352'
down_revision = '8ecfe7dd657c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('resource_recommendation_vector', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('skill', sa.Column('skill_embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'skill_embedding')
    op.drop_column('skill', 'resource_recommendation_vector')
    # ### end Alembic commands ###
